version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0
  maven: circleci/maven@0.0.12
jobs:
  build:
    machine: true
    steps:
      - maven/test
      - shiftleft/analyze:
          app: hello-shiftleft
          target: target/hello-shiftleft-0.0.1.jar
          language: java
workflows:
  version: 2.1
  workflow:
    jobs:
      
      - build
