version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0
workflows:
  version: 2.1
  workflow:
    jobs:
      - shiftleft/analyze:
          app: helloshiftleft
          target: target/hello-shiftleft-0.0.1.jar
          language: java
