version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mvn package
      - shiftleft/analyze:
          app: hello-shiftleft
          target: target/hello-shiftleft-0.0.1.jar
          language: java
workflows:
  workflow:
    jobs:
      - build
